package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root := filepath.Join("..", "..")
	sourceDir := filepath.Join(root, "docs", "baselines")
	outputPath := filepath.Join(".", "embedded_gen.go")

	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		fail("read baseline directory: %v", err)
	}

	names := make([]string, 0, len(entries))
	contents := make(map[string]string, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		name := entry.Name()
		path := filepath.Join(sourceDir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			fail("read baseline %q: %v", path, err)
		}
		names = append(names, name)
		contents[name] = string(data)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buf.WriteString("package baseline\n\n")
	buf.WriteString("var embeddedTemplates = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(&buf, "\t%q: %q,\n", name, contents[name])
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fail("format generated source: %v", err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fail("write generated source: %v", err)
	}
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
